jdbc.url=jdbc:postgresql://localhost:5432/schooldb
jdbc.username=postgres
jdbc.password=Dkdinesh6229
jdbc.driver=org.postgresql.Driver










#jdbc.url=jdbc:postgresql://localhost:5432/schooldb
#jdbc.username=postgres
#jdbc.password=Dkdinesh6229
#jdbc.driver=org.postgresql.Driver
